-- Esquema para la aplicación de boletería
-- Ejecuta estos comandos en el SQL editor de Supabase

create table if not exists public.vendedores (
    id bigint generated by default as identity primary key,
    nombre text not null unique,
    created_at timestamptz not null default now()
);

create table if not exists public.boletas (
    numero integer primary key,
    estado text not null default 'disponible' check (estado in ('disponible', 'vendida')),
    vendedor text,
    fecha timestamptz,
    comprador text,
    celular text
);

create table if not exists public.configuracion_sistema (
    id integer primary key,
    total_boletas integer not null,
    precio_boleta integer not null,
    actualizado_por text,
    fecha_actualizacion timestamptz
);

-- Índices de apoyo
create index if not exists idx_boletas_estado on public.boletas (estado);
create index if not exists idx_boletas_vendedor on public.boletas (vendedor);
