-- Esquema para la aplicación de boletería
-- Ejecuta estos comandos en el SQL editor de Supabase

create table if not exists public.vendedores (
    id bigint generated by default as identity primary key,
    nombre text not null,
    username text not null,
    password_hash text not null,
    sitio_slug text not null default 'default',
    created_at timestamptz not null default now()
);

create table if not exists public.administradores (
    id bigint generated by default as identity primary key,
    username text not null,
    password_hash text not null,
    sitio_slug text not null default 'default',
    created_at timestamptz not null default now()
);

insert into public.administradores (username, password_hash, sitio_slug)
select 'admin' as username,
       '6faba6e4ed724c5b54fad19eca98923e2198cdbba78db5e74672c83217fb33a6' as password_hash,
       'default' as sitio_slug
where not exists (
    select 1 from public.administradores where username = 'admin' and sitio_slug = 'default'
);

alter table if exists public.vendedores
    add column if not exists username text;

alter table if exists public.vendedores
    add column if not exists password_hash text;

update public.vendedores
set username = regexp_replace(lower(nombre), '\s+', '', 'g')
where username is null;

update public.vendedores
set password_hash = 'cdf12b938b75e283a1f4a864ef51b810f5935e98f779705df390066203f0ba66'
where password_hash is null;

alter table if exists public.vendedores
    alter column username set not null;

alter table if exists public.vendedores
    alter column password_hash set not null;

-- Estrategia: una sola tabla por entidad, aislada por la columna sitio_slug
alter table if exists public.vendedores
    add column if not exists sitio_slug text not null default 'default';

alter table if exists public.administradores
    add column if not exists sitio_slug text not null default 'default';

alter table if exists public.boletas
    add column if not exists sitio_slug text not null default 'default';

alter table if exists public.configuracion_sistema
    add column if not exists sitio_slug text not null default 'default';

-- Claves e índices por sitio
alter table if exists public.boletas
    drop constraint if exists boletas_pkey;

alter table if exists public.boletas
    add constraint boletas_pkey primary key (sitio_slug, numero);

alter table if exists public.vendedores
    drop constraint if exists vendedores_nombre_key;

alter table if exists public.vendedores
    drop constraint if exists vendedores_username_key;

alter table if exists public.vendedores
    add constraint vendedores_nombre_sitio_key unique (sitio_slug, nombre);

alter table if exists public.vendedores
    add constraint vendedores_username_sitio_key unique (sitio_slug, username);

alter table if exists public.administradores
    drop constraint if exists administradores_username_key;

alter table if exists public.administradores
    add constraint administradores_username_sitio_key unique (sitio_slug, username);

alter table if exists public.configuracion_sistema
    drop constraint if exists configuracion_sistema_pkey;

alter table if exists public.configuracion_sistema
    add constraint configuracion_sistema_pkey primary key (sitio_slug, id);

create table if not exists public.boletas (
    sitio_slug text not null default 'default',
    numero integer not null,
    estado text not null default 'disponible' check (estado in ('disponible', 'reservada', 'vendida')),
    vendedor text,
    fecha timestamptz,
    comprador text,
    celular text
);

create table if not exists public.configuracion_sistema (
    sitio_slug text not null default 'default',
    id integer not null,
    total_boletas integer not null,
    precio_boleta integer not null,
    actualizado_por text,
    fecha_actualizacion timestamptz
);

alter table if exists public.boletas
    drop constraint if exists boletas_estado_check;

alter table if exists public.boletas
    add constraint boletas_estado_check
        check (estado in ('disponible', 'reservada', 'vendida'));

-- Índices de apoyo
create index if not exists idx_boletas_sitio_estado on public.boletas (sitio_slug, estado);
create index if not exists idx_boletas_sitio_vendedor on public.boletas (sitio_slug, vendedor);
create index if not exists idx_vendedores_sitio_username on public.vendedores (sitio_slug, username);
create index if not exists idx_vendedores_sitio_nombre on public.vendedores (sitio_slug, nombre);
create index if not exists idx_configuracion_sitio on public.configuracion_sistema (sitio_slug);
create index if not exists idx_administradores_sitio_username on public.administradores (sitio_slug, username);

-- Políticas de Row Level Security para aislar datos por sitio
alter table if exists public.boletas enable row level security;
alter table if exists public.vendedores enable row level security;
alter table if exists public.administradores enable row level security;
alter table if exists public.configuracion_sistema enable row level security;

alter table if exists public.boletas force row level security;
alter table if exists public.vendedores force row level security;
alter table if exists public.administradores force row level security;
alter table if exists public.configuracion_sistema force row level security;

create policy boletas_site_isolation_anon on public.boletas
    for all to anon
    using (sitio_slug = coalesce((current_setting('request.headers', true)::json->>'x-site-slug'), 'default'))
    with check (sitio_slug = coalesce((current_setting('request.headers', true)::json->>'x-site-slug'), 'default'));

create policy boletas_site_isolation_authenticated on public.boletas
    for all to authenticated
    using (sitio_slug = coalesce((current_setting('request.headers', true)::json->>'x-site-slug'), 'default'))
    with check (sitio_slug = coalesce((current_setting('request.headers', true)::json->>'x-site-slug'), 'default'));

create policy boletas_service_full_access on public.boletas
    for all to service_role
    using (true)
    with check (true);

create policy vendedores_site_isolation_anon on public.vendedores
    for all to anon
    using (sitio_slug = coalesce((current_setting('request.headers', true)::json->>'x-site-slug'), 'default'))
    with check (sitio_slug = coalesce((current_setting('request.headers', true)::json->>'x-site-slug'), 'default'));

create policy vendedores_site_isolation_authenticated on public.vendedores
    for all to authenticated
    using (sitio_slug = coalesce((current_setting('request.headers', true)::json->>'x-site-slug'), 'default'))
    with check (sitio_slug = coalesce((current_setting('request.headers', true)::json->>'x-site-slug'), 'default'));

create policy vendedores_service_full_access on public.vendedores
    for all to service_role
    using (true)
    with check (true);

create policy administradores_site_isolation_anon on public.administradores
    for all to anon
    using (sitio_slug = coalesce((current_setting('request.headers', true)::json->>'x-site-slug'), 'default'))
    with check (sitio_slug = coalesce((current_setting('request.headers', true)::json->>'x-site-slug'), 'default'));

create policy administradores_site_isolation_authenticated on public.administradores
    for all to authenticated
    using (sitio_slug = coalesce((current_setting('request.headers', true)::json->>'x-site-slug'), 'default'))
    with check (sitio_slug = coalesce((current_setting('request.headers', true)::json->>'x-site-slug'), 'default'));

create policy administradores_service_full_access on public.administradores
    for all to service_role
    using (true)
    with check (true);

create policy configuracion_site_isolation_anon on public.configuracion_sistema
    for all to anon
    using (sitio_slug = coalesce((current_setting('request.headers', true)::json->>'x-site-slug'), 'default'))
    with check (sitio_slug = coalesce((current_setting('request.headers', true)::json->>'x-site-slug'), 'default'));

create policy configuracion_site_isolation_authenticated on public.configuracion_sistema
    for all to authenticated
    using (sitio_slug = coalesce((current_setting('request.headers', true)::json->>'x-site-slug'), 'default'))
    with check (sitio_slug = coalesce((current_setting('request.headers', true)::json->>'x-site-slug'), 'default'));

create policy configuracion_service_full_access on public.configuracion_sistema
    for all to service_role
    using (true)
    with check (true);
