-- Esquema para la aplicación de boletería
-- Ejecuta estos comandos en el SQL editor de Supabase

create table if not exists public.vendedores (
    id bigint generated by default as identity primary key,
    nombre text not null unique,
    username text not null unique,
    password_hash text not null,
    created_at timestamptz not null default now()
);

alter table if exists public.vendedores
    add column if not exists username text;

alter table if exists public.vendedores
    add column if not exists password_hash text;

update public.vendedores
set username = regexp_replace(lower(nombre), '\s+', '', 'g')
where username is null;

update public.vendedores
set password_hash = 'cdf12b938b75e283a1f4a864ef51b810f5935e98f779705df390066203f0ba66'
where password_hash is null;

alter table if exists public.vendedores
    alter column username set not null;

alter table if exists public.vendedores
    alter column password_hash set not null;

alter table if exists public.vendedores
    add constraint if not exists vendedores_username_key unique (username);

create table if not exists public.boletas (
    numero integer primary key,
    estado text not null default 'disponible' check (estado in ('disponible', 'reservada', 'vendida')),
    vendedor text,
    fecha timestamptz,
    comprador text,
    celular text
);

create table if not exists public.configuracion_sistema (
    id integer primary key,
    total_boletas integer not null,
    precio_boleta integer not null,
    actualizado_por text,
    fecha_actualizacion timestamptz
);

alter table if exists public.boletas
    drop constraint if exists boletas_estado_check;

alter table if exists public.boletas
    add constraint boletas_estado_check
        check (estado in ('disponible', 'reservada', 'vendida'));

-- Índices de apoyo
create index if not exists idx_boletas_estado on public.boletas (estado);
create index if not exists idx_boletas_vendedor on public.boletas (vendedor);
create index if not exists idx_vendedores_username on public.vendedores (username);
